# Copyright (c) Facebook, Inc. and its affiliates.
# This source code is licensed under the CC-BY-NC license found in the
# LICENSE file in the root directory of this source tree.

NBV:
  budget: 5

experiment:
  batch_size: 16
  experiment_id: pretrained
  id: pretrained
  logdir: logs
  num_epochs: 1000
  patience: 50
  randomseed: 0

loss:
  bce_loss: 0.1
  iou_loss: 0.01
  num_samples: 1500

model:
  CNN_ker_size: 3
  decoder_activation: relu
  decoder_layers: 3
  hidden_size: 250
  image_embedding: 45
  initial_size: 32
  layers_per_block: 6
  num_CNN_blocks: 4

optimizer:
  lr: 0.0004
  type: Adam
