# Copyright (c) Facebook, Inc. and its affiliates.
# This source code is licensed under the CC-BY-NC license found in the
# LICENSE file in the root directory of this source tree.

experiment:
  experiment_id: test # name of the experiment
  id: test # name of the instance in the experiment
  logdir: logs # location of logs
  randomseed: 42  # seed
  patience: 50 # how many epoch without improvement before stopping
  batch_size: 1 # batch size 16
  num_epochs: 20 # number of epochs 1000

model:
  image_embedding: 64 # size of the image embedding from the CNN
  hidden_size: 10 # hidden layer size for basically every non CNN layer 200
  decoder_layers: 3 # number of hidden layers
  CNN_ker_size: 3 # size of image kernels
  num_CNN_blocks: 4 # number of times to half image dimensions in CNN
  layers_per_block: 8 # number of layers for each dimensions size in CNN
  initial_size: 16 # initial size of CNN channel in CNN

optimizer:
  lr: 0.0005 # learning rate

loss:
  num_rays: 32 # number of pixels to samples from each target image which training

NBV:
  budget: 2 # how many images we want to use 5


